# Generated by Django 5.0 on 2024-01-04 16:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handbag",
            name="image_link",
            field=models.URLField(),
        ),
    ]
