# Generated by Django 5.0 on 2024-01-12 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="handbag",
            name="color",
            field=models.CharField(default="Unknown", max_length=255),
        ),
    ]
