# Generated by Django 5.0 on 2024-01-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("drf_app", "0002_alter_handbag_image_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="handbag",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10, max_length=255),
        ),
    ]
